name: Update awesome list

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@latest
        with:
          api-token: ${{ secrets.API_TOKEN }}
          template-path: "template/TEMPLATE.ejs"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-email: 'github-actions[bot]@users.noreply.github.com'
          github-name: 'github-actions[bot]'
          output-filename: STARS.md
